Repository zjunior-infra/Dashboard, pull requests merged in 2023-04, with the labels that each got.

#3 API security
  next.config.js
  package.json
  pages/api/hello.ts
  pages/api/jobs/confirm.ts
  vercel.json
Labels: bug, enhancement

#4 API CORS
  vercel.json
Labels: bug

#6 Modify the api cros
  vercel.json
Labels: enhancement

#11 Adding a a button to fire the crawler
  components/DataGrid.tsx
  package-lock.json
  package.json
  pages/api/jobs/crawler.ts
  pages/index.tsx
  tailwind.config.js
Labels: enhancement, task

#12 :zap: using client side fetching
  components/Layout.tsx
  pages/api/jobs/jobs.json.ts
  pages/index.tsx
Labels: bug
