Repository zjunior-infra/Dashboard, pull requests merged in 2023-05, with the labels that each got.

#15 fixing the 500 internel server error
  package.json
  pages/index.tsx
  prisma/schema.prisma
Labels: bug

#17 popup won't disappear bug
  components/DataGrid.tsx
Labels: bug

#20 Seeds
  docker-compose.yml
  package-lock.json
  package.json
  prisma/seed.ts
Labels: documentation

#19 Update multiple jobs
  components/DataGrid.tsx
  components/UserAction.tsx
Labels: bug

#27 Fixing the missing column
  components/DataGrid.tsx
  pages/api/jobs/jobs.json.ts
Labels: bug

#28 optimize the start limit, Vercel
  components/DataGrid.tsx
  components/UserAction.tsx
  pages/api/confirm.ts
  pages/api/crawler.ts
  pages/api/create.ts
  pages/api/delete.ts
  pages/api/hello.ts
  pages/api/update.ts
Labels: enhancement
